# Permalinks
permalink:           pretty

# Setup
title:               From model field to power yield
tagline:             A responsive blog theme that illustrates reading progress. Suited for continous reading.
url:                 http://peter9192.github.io
baseurl:             /energy-meteo
analytics_id:

# Owner/author information
owner:
  name:           Peter Kalverla
  avatar:         avatar.png
  bio:            "PhD student"
  email:          alex@collectivelymade.com
  twitter:        alexanderussell
  github:         alexanderussell
  instagram:      alexanderussell
  dribbble:       alexanderussell
  location:       "Lincoln, NE"


# Custom vars
version:             2.0.0
github:
  repo:

# Pagination
# paginate: 5
# paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
